-- ============================================================================
-- HEDIS CQL Oracle Schema
-- New tables for CQL-based measure processing
-- ============================================================================

-- CQL measure definitions
CREATE TABLE SMA_CQL_MEASURES (
  MEASURE_ID    VARCHAR2(20)  NOT NULL,
  VERSION       VARCHAR2(20)  NOT NULL,
  CQL_TEXT      CLOB          NOT NULL,
  STATUS        CHAR(1)       DEFAULT 'A',  -- A=active, I=inactive
  CREATED_DATE  DATE          DEFAULT SYSDATE,
  MODIFIED_DATE DATE          DEFAULT SYSDATE,
  PRIMARY KEY (MEASURE_ID, VERSION)
);

COMMENT ON TABLE SMA_CQL_MEASURES IS 'CQL measure definitions (replaces hardcoded C++ rules)';
COMMENT ON COLUMN SMA_CQL_MEASURES.STATUS IS 'A=Active, I=Inactive';

-- Value sets referenced by CQL measures
CREATE TABLE SMA_CQL_VALUESETS (
  VALUESET_NAME VARCHAR2(200) NOT NULL,
  CODE          VARCHAR2(50)  NOT NULL,
  CODE_SYSTEM   VARCHAR2(20)  NOT NULL,
  DISPLAY       VARCHAR2(500),
  VERSION       VARCHAR2(20)  DEFAULT 'HEDIS-2026',
  PRIMARY KEY (VALUESET_NAME, CODE, CODE_SYSTEM, VERSION)
);

CREATE INDEX IDX_CQL_VS_CODE ON SMA_CQL_VALUESETS (CODE, CODE_SYSTEM);
CREATE INDEX IDX_CQL_VS_NAME ON SMA_CQL_VALUESETS (VALUESET_NAME, VERSION);

COMMENT ON TABLE SMA_CQL_VALUESETS IS 'HEDIS value sets: code lists for clinical concepts';

-- Results staging (written by worker servers, one partition per server)
CREATE TABLE SMA_CQL_RESULTS_STG (
  PARTITION_ID      NUMBER(10)    NOT NULL,
  PATIENT_ID        VARCHAR2(30)  NOT NULL,
  MEASURE_ID        VARCHAR2(20)  NOT NULL,
  INITIAL_POP       CHAR(1),
  DENOMINATOR       CHAR(1),
  NUMERATOR         CHAR(1),
  DENOM_EXCLUSION   CHAR(1),
  DENOM_EXCEPTION   CHAR(1),
  FAILURE_DATE      DATE,
  NUMERIC_RESULT    NUMBER(10,4),
  PROCESS_DATE      DATE DEFAULT SYSDATE
) PARTITION BY RANGE (PARTITION_ID) (
  PARTITION p1  VALUES LESS THAN (2),
  PARTITION p2  VALUES LESS THAN (3),
  PARTITION p3  VALUES LESS THAN (4),
  PARTITION p4  VALUES LESS THAN (5),
  PARTITION p5  VALUES LESS THAN (6),
  PARTITION p6  VALUES LESS THAN (7),
  PARTITION p7  VALUES LESS THAN (8),
  PARTITION p8  VALUES LESS THAN (9),
  PARTITION p9  VALUES LESS THAN (10),
  PARTITION p10 VALUES LESS THAN (11),
  PARTITION p11 VALUES LESS THAN (12),
  PARTITION p12 VALUES LESS THAN (13),
  PARTITION p13 VALUES LESS THAN (14),
  PARTITION p14 VALUES LESS THAN (15),
  PARTITION p15 VALUES LESS THAN (16),
  PARTITION p16 VALUES LESS THAN (17),
  PARTITION p17 VALUES LESS THAN (18),
  PARTITION p18 VALUES LESS THAN (19),
  PARTITION p19 VALUES LESS THAN (20),
  PARTITION p20 VALUES LESS THAN (21),
  PARTITION p21 VALUES LESS THAN (22),
  PARTITION p22 VALUES LESS THAN (23),
  PARTITION p23 VALUES LESS THAN (24),
  PARTITION p24 VALUES LESS THAN (25)
);

CREATE INDEX IDX_CQL_STG_PAT ON SMA_CQL_RESULTS_STG (PATIENT_ID, MEASURE_ID) LOCAL;

COMMENT ON TABLE SMA_CQL_RESULTS_STG IS 'Staging table for worker-produced results (range-partitioned by server)';

-- Production results (after merge)
CREATE TABLE SMA_CQL_RESULTS (
  PATIENT_ID        VARCHAR2(30)  NOT NULL,
  MEASURE_ID        VARCHAR2(20)  NOT NULL,
  INITIAL_POP       CHAR(1),
  DENOMINATOR       CHAR(1),
  NUMERATOR         CHAR(1),
  DENOM_EXCLUSION   CHAR(1),
  FAILURE_DATE      DATE,
  NUMERIC_RESULT    NUMBER(10,4),
  JOB_ID            VARCHAR2(50),
  PROCESS_DATE      DATE,
  PRIMARY KEY (PATIENT_ID, MEASURE_ID)
);

CREATE INDEX IDX_CQL_RESULTS_MEASURE ON SMA_CQL_RESULTS (MEASURE_ID, DENOMINATOR, NUMERATOR);
CREATE INDEX IDX_CQL_RESULTS_JOB     ON SMA_CQL_RESULTS (JOB_ID);

COMMENT ON TABLE SMA_CQL_RESULTS IS 'Production measure results (one row per patient per measure)';

-- Aggregated rates per measure per job
CREATE TABLE SMA_CQL_MEASURE_RATES (
  JOB_ID            VARCHAR2(50)  NOT NULL,
  MEASURE_ID        VARCHAR2(20)  NOT NULL,
  INITIAL_POP_COUNT NUMBER(10),
  DENOM_COUNT       NUMBER(10),
  NUMER_COUNT       NUMBER(10),
  EXCLUSION_COUNT   NUMBER(10),
  RATE              NUMBER(5,2),  -- numerator/denominator %
  PROCESS_DATE      DATE,
  PRIMARY KEY (JOB_ID, MEASURE_ID)
);

COMMENT ON TABLE SMA_CQL_MEASURE_RATES IS 'Aggregated HEDIS rates per measure per processing job';

-- ============================================================================
-- Partition control table (mirrors existing SMA_PARTITIONS_CTL)
-- ============================================================================
-- Note: If SMA_PARTITIONS_CTL already exists in the environment,
-- this is for reference only. The worker uses the same schema.

/*
CREATE TABLE SMA_PARTITIONS_CTL (
  PARTITION_ID    NUMBER(10)    NOT NULL PRIMARY KEY,
  JOB_ID          VARCHAR2(50)  NOT NULL,
  START_ID        NUMBER(15),
  END_ID          NUMBER(15),
  STATUS          CHAR(1)       DEFAULT 'P',  -- P=pending, R=running, C=complete, F=failed
  HOSTNAME        VARCHAR2(100),
  BATCH_SIZE      NUMBER(10),
  RUN_DATE        DATE,
  START_TIME      DATE,
  END_TIME        DATE,
  TOTAL_PATIENTS  NUMBER(10),
  COVERED_PATIENTS NUMBER(10),
  ERROR_PATIENTS  NUMBER(10),
  ALERTS          NUMBER(10),
  ELAPSED_SEC     NUMBER(10,2),
  ERROR_MSG       VARCHAR2(2000),
  CREATED_DATE    DATE DEFAULT SYSDATE
);

CREATE TABLE SMA_PARTITIONS_PARAMS (
  JOB_ID          VARCHAR2(50)  NOT NULL,
  PARAM_NAME      VARCHAR2(100) NOT NULL,
  PARAM_VALUE     VARCHAR2(500),
  PRIMARY KEY (JOB_ID, PARAM_NAME)
);
*/
